# Generated by Django 4.2.3 on 2023-07-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video_details',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_title', models.CharField(max_length=150)),
                ('video_category', models.CharField(max_length=100)),
                ('video_thumbnail', models.ImageField(upload_to='thumbnail')),
                ('video_views', models.CharField(max_length=50)),
                ('video_videofile', models.FileField(upload_to='video')),
            ],
        ),
    ]
