# Generated by Django 4.2.3 on 2023-07-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_details',
            name='video_views',
            field=models.IntegerField(default=0),
        ),
    ]
