# Generated by Django 4.2.3 on 2023-07-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0002_alter_video_details_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_details',
            name='video_channelname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='video_details',
            name='video_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
