# Generated by Django 4.2.3 on 2023-07-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0003_video_details_video_channelname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_details',
            name='video_timestamp',
            field=models.DateTimeField(),
        ),
    ]
