# Generated by Django 4.2.3 on 2023-07-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0004_alter_video_details_video_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_details',
            name='video_description',
            field=models.TextField(default=''),
        ),
    ]
