# Generated by Django 4.2.3 on 2023-07-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0005_video_details_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_details',
            name='video_duration',
            field=models.CharField(default='', max_length=20),
        ),
    ]
