# Generated by Django 4.2.3 on 2023-08-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0008_user_videos_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_videos_history',
        ),
    ]
