# Generated by Django 4.2.3 on 2023-08-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0012_user_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_uploads',
            name='video_thumbnail',
            field=models.ImageField(upload_to='upload_thumbnail'),
        ),
    ]
