# Generated by Django 4.2.3 on 2023-08-03 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube_app', '0013_alter_user_uploads_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_uploads',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video_details',
            name='video_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
