# Generated by Django 4.2.3 on 2023-08-06 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0018_alter_comments_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_videos_history',
            name='user_videos',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='youtube_app.user_uploads'),
        ),
    ]
