# Generated by Django 4.2.3 on 2023-08-07 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0021_alter_user_videos_history_user_videos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_videos_history',
            name='user_videos',
        ),
        migrations.AlterField(
            model_name='user_videos_history',
            name='videos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_app.video_details'),
        ),
    ]
